- README.md
> ### Title
> Docs: README.md 팀원 및 BE code convention 수정
> ### PR Type
>
> - [x] DOCS: 문서 추가 및 수정
>
>
> docs: README.md 팀원 및 BE code convention 수정

- server/config/urls.py
- server/expenses/models.py
- server/expenses/serializers.py
- server/expenses/urls.py
- server/expenses/views.py
> ### Title
> Feat: expenses, fixed_expenses API
> ### PR Type
>
> expenses, fixed_expenses API 구현
>
> feat: expenses, fixed_expenses API

- server/.deploy.env
- server/config/settings.py
- server/config/urls.py
- server/members/serializers.py
- server/members/urls.py
- server/members/views.py
> ### Title
> Feat: member 회원가입 및 로그인 기능 수정 / member 조회, 수정, 삭제 기능 구현
> ### PR Type
>
> 멤버 로그인 , 회원가입 및 멤버 조회 삭제 수정 기능 구현및 postman 백엔드 자체 테스트확인
>
> feat: 회원가입및 로그인 API 수정 및 회원정보 조회, 수정, 삭제 API 기능 구현

- server/config/settings.py
- server/config/urls.py
- server/expenses/admin.py
- server/expenses/models.py
- server/expenses/serializers.py
- server/expenses/urls.py
- server/expenses/views.py
- server/members/admin.py
- server/members/models.py
- server/members/views.py
- server/reports/admin.py
- server/reports/apps.py
- server/reports/models.py
- server/reports/tests.py
- server/reports/urls.py
- server/reports/views.py
> ### Title
> Feat: 지출, 고정지출 CRUD 기능 구현 및 보고서 조회기능 구현
> ### PR Type
>
> 브랜치 명과는 다른 작업을 조금 했지만 유저 살짝 수정하고 , 지출및 고정지출 생성 조회 수정 삭제 기능구현 , 보고서 조회 기능 구현
>
> Be} password encryption

- client/src/App.tsx
- client/src/Pages/Login/Login.tsx
- client/src/Pages/SignUp/Signup.tsx
- client/src/api/axios.ts
- client/src/api/requests.ts
> ### Title
>
> - Feat: 인터셉터 기능 구현
> ### PR Type
>
>
> - 토큰 자동갱신
>
> - 없음
> Fe] interceptors

- server/budgets/serializers.py
- server/budgets/urls.py
- server/budgets/views.py
- server/config/settings.py
- server/members/serializers.py
- server/members/urls.py
- server/members/views.py
- server/reports/views.py
> ### Title
> Fix: 예산 CRUD 기능 수정
> ### PR Type
>
> 예산 생성시 멤버 정보 등록 안되는 버그 수정 및 예산 시리얼라이저 수정
>
> Fix: 예산 CRUD 기능 수정

- server/members/views.py
> ### Title
>  Chore: 줄바꿈
> ### PR Type
>
> - [x] CHORE: 기타 작업
> 딱히 한거 없고 줄바꿈했습니다
>
> Chore: 줄바꿈 수정

- client/src/Components/Charts/BarChart.tsx
- client/src/Components/Charts/DoughnutChartCategory.tsx
- client/src/Components/Charts/DoughnutChartPlace.tsx
- client/src/Components/Header/Header.tsx
- client/src/Pages/Login/Login.tsx
- client/src/Pages/MonthlyReport/MonthlyReport.tsx
- client/src/Pages/SignUp/Signup.tsx
Title
Feat : memberId 로컬스토리지에서 가져와서 해당 Id의 데이터로 레포트 띄우기
PR Type
Description
memberId 로컬스토리지에서 가져와서 해당 Id의 데이터로 레포트 띄우기
Discussion
보고서 페이지 수정 이외에
1. 로그인 memberId 로컬 스토리지 저장하는 코드 추가
2. Header에서 보고서 클릭하면 보고서 페이지 넘어가는 navigation 추가
> Feat : memberId 로컬스토리지에서 가져와서 해당 Id의 데이터로 레포트 띄우기

- client/src/App.tsx
- client/src/Components/BudgetNExpensesTables/BudgetHistoryTableCell.css.ts
- client/src/Components/BudgetNExpensesTables/BudgetHistoryTableCell.tsx
- client/src/Components/BudgetNExpensesTables/ExpensesRegiTableCell.css.ts
- client/src/Components/BudgetNExpensesTables/ExpensesRegiTableCell.tsx
- client/src/Components/BudgetRegTable/BudgetRegTable.tsx
- client/src/Components/SelectBox/Select.tsx
- client/src/Components/SideBar.tsx/FixedExpenses/FixedExpenses.tsx
- client/src/Components/SideBar.tsx/SideBar.css.ts
- client/src/Components/SideBar.tsx/SideBar.tsx
- client/src/Pages/BudgetNExpenses/BudgetNExpenses.css.ts
- client/src/Pages/BudgetNExpenses/BudgetNExpenses.tsx
- client/src/Pages/Login/Login.tsx
- client/src/Pages/SignUp/Signup.tsx
- client/src/api/axios.ts
- client/src/api/budgetRegRequest.ts
- client/src/api/categoriesRequest.ts
- client/src/api/fixedRequest.ts
- client/src/store/useBudgetStore.ts
> ### Title
>
> - [Feat] 전체예산 등록 삭제, 고정지출 등록삭제수정
> ### PR Type
>
>
> - crud 다 함
> - 
>
> - 데이터가 없으면 행추가가 안된다
> Fe] reg expenditure

- client/src/Components/Scheduler/Calendar.css.ts
- client/src/Components/Scheduler/Calendar.tsx
- client/src/Pages/Login/Login.tsx
Title
[Feat] : expense 데이터 get 해서 해당 날짜에 표시하기
PR Type
[X] FEAT: 새로운 기능 구현
[ ]  ADD : 에셋 파일 추가
[ ]  FIX: 버그 수정
[ ]  DOCS: 문서 추가 및 수정
[ ]  STYLE: 포맷팅 변경
[ ]  REFACTOR: 코드 리팩토링
[ ]  TEST: 테스트 관련
[ ]  DEPLOY: 배포 관련
[ ]  CONF: 빌드, 환경 설정
[X]  CHORE: 기타 작업
Description
react-calendar -> dist -> Calendar.css 파일 수정
Discussion
> [Feat] : expense 데이터 get 해서 해당 날짜에 표시하기

- client/src/Components/BudgetNExpensesTables/ExpensesRegiTableCell.tsx
- client/src/Components/BudgetRegTable/BudgetRegTable.tsx
- client/src/Components/ExpendituresList/ExpenditureList.tsx
- client/src/Components/SideBar.tsx/SideBar.css.ts
- client/src/Components/SideBar.tsx/SideBar.tsx
- client/src/Pages/BudgetNExpenses/BudgetNExpenses.tsx
- client/src/Pages/BudgetRegister/BudgetRegister.css.ts
- client/src/Pages/BudgetRegister/BudgetRegister.tsx
- client/src/Pages/MainPage/Main.css.ts
- client/src/Pages/MainPage/Main.tsx
- client/src/api/categoriesRequest.ts
- client/src/api/expenseRequest.ts
> ### Title
>
> [Feat] 지출 CRUD, 타입에러 수정
> ### PR Type
>
>
> - 지출 CRUD
> 
>
> - 등록 삭제 수정시 바로 반영 안됨 이슈
> Fe] reg expense

- client/src/App.tsx
- client/src/Components/BudgetNExpensesTables/BudgetHistoryTableCell.tsx
- client/src/Components/BudgetNExpensesTables/ExpensesRegiTableCell.tsx
- client/src/Components/ExpendituresList/ExpenditureList.tsx
- client/src/Components/Header/Header.css.ts
- client/src/Components/Header/Header.tsx
- client/src/Pages/BudgetNExpenses/BudgetNExpenses.tsx
- client/src/constants/components-contants.ts
> ### Title
>
> [Refector]  헤더, 예산,고정지출,지출 코드 변경
> ### PR Type
>
> - [x] REFACTOR: 코드 리팩토링
>
> 상태변경시 화면 리렌더링, 헤더 경로 연결 
> 
>
> 타입에러를 고쳐야 합니다.
> Refector: 헤더, 예산,고정지출,지출 코드 변경

- server/.gitignore
- server/Dockerfile
- server/budgets/urls.py
- server/budgets/views.py
- server/config/settings.py
- server/docker-compose.yml
- server/entrypoint.sh
- server/expenses/urls.py
- server/expenses/views.py
- server/members/urls.py
- server/members/views.py
- server/reports/urls.py
- server/reports/views.py
> ### Title
> Feat: 사용자 프로필 이미지 업로드기능 구현
> ### PR Type
>
> 사용자 프로필 이미지 업로드기능 구현 / member_id 를 access_token 값에서 가져오는 방식으로 변경
> refresh 토큰 request body 어떻게 넘겨주는지만 확인
> Feat: 사용자 프로필 이미지 업로드기능 구현

- server/poetry.lock
- server/pyproject.toml
> ### Title
> Conf: boto3 라이브러리 설치
> ### PR Type
>
>
>
> Conf: boto3 라이브러리 설치

- client/src/Components/Charts/BarChart.tsx
- client/src/Components/Charts/DoughnutChartCategory.tsx
- client/src/Components/Charts/DoughnutChartPlace.tsx
- client/src/Pages/MonthlyReport/MonthlyReport.tsx
>
> [Chore] : 타입 에러 수정
> ### PR Type
>
>
> Chore : 타입 에러 수정

- client/src/components/Charts/DoughnutChartCategory.tsx
- client/src/components/Charts/DoughnutChartPlace.tsx
- client/src/pages/MonthlyReport/MonthlyReport.tsx
>
> - Feat : Report 카테고리 도넛차트 Top5 내역 없을 때도 뜨는 문제 해결
> ### PR Type
>
> - [X] FEAT: 새로운 기능 구현
>
> 도넛 차트 카테고리 Top 5 리스트 지출 내역 없는 경우에도 뜨는 문제 있어서 해결
> 차트 2가지 변수명 서로 맞췄습니다.
>
> - 추후 논의할 점에 대해 작성해주세요.
> Feat : Report 카테고리 도넛차트 Top5 내역 없을 때도 뜨는 문제 해결

- client/src/components/BudgetNExpensesTables/BudgetHistoryTableCell.tsx
- client/src/components/BudgetNExpensesTables/ExpensesRegiTableCell.tsx
- client/src/components/SideBar.tsx/SideBar.tsx
- client/src/pages/BudgetNExpenses/BudgetNExpenses.tsx
- client/src/pages/Mypage/Mypage.tsx
> ### Title
>
> - [Chore] 등록,에러뜨는 경우 toast 알림 처리
> ### PR Type
>
> - [x] CHORE: 기타 작업
>
> - 값 입력안하면 알림 띄우기
>
> - 더 해야합니다
> Chore: toast 알림처리중

- client/src/App.tsx
- client/src/components/BudgetNExpensesTables/BudgetHistoryTableCell.tsx
- client/src/components/Charts/DoughnutChartCategory.tsx
- client/src/components/Charts/DoughnutChartPlace.tsx
- client/src/components/ExpendituresList/ExpenditureList.tsx
- client/src/components/Scheduler/Calendar.tsx
- client/src/pages/BudgetNExpenses/BudgetNExpenses.tsx
- client/src/pages/Login/Login.tsx
- client/src/pages/MonthlyReport/MonthlyReport.tsx
>
> - Chore : 데이터 예외처리
> ### PR Type
>
>
> 데이터 없는 경우에 에러 메시지 or div로 문구 띄워놓음
>
> - 이렇게 하는게 맞나 모르겠는게 문제
> Chore : 데이터 예외처리

- client/src/App.tsx
- client/src/components/BudgetNExpensesTables/ExpensesRegiTableCell.tsx
- client/src/components/BudgetRegTable/BudgetRegTable.tsx
- client/src/components/ExpendituresList/ExpenditureList.tsx
- client/src/components/SideBar.tsx/SideBar.tsx
- client/src/main.tsx
- client/src/pages/BudgetNExpenses/BudgetNExpenses.tsx
- client/src/pages/BudgetRegister/BudgetRegister.tsx
- client/src/pages/Login/Login.tsx
- client/src/pages/MainPage/Main.tsx
- client/src/pages/Mypage/Mypage.tsx
> ### Title
>
> - [Fix] 오류사항 수정
> ### PR Type
>
>
> - 로그인, 로그아웃시 페이지 이동안됨, 사이드바 지출 데이터 없을 경우 Null로 페이지 자체 안뜸, 전체예산 등록시 사이드바 값 반영안됨, 캘린더 날짜 안바뀜 오류 해결 , 값 미입력시 알림창 띄움
>
> - 계속 테스트 해봐야 할듯
> [FE] 오류 사항 수정

- server/budgets/views.py
- server/config/settings.py
- server/expenses/views.py
- server/members/serializers.py
- server/members/views.py
- server/reports/serializers.py
- server/reports/views.py
> ### Title
> Fix: Swagger-ui 설정 - Serializers.py 수정
> ### PR Type
>
>
>
> Fix: Swagger-ui 설정 - Serializers.py 수정

- server/docker-compose.yml
- server/entrypoint.sh
- server/nginx/django.conf
- server/poetry.lock
- server/pyproject.toml
> ### Title
> Deploy: nginx, gunicorn 설정 및 docker-compose, dockerfile 수정
> ### PR Type
>
> - [x] DEPLOY: 배포 관련
>
>
> Deploy: nginx, gunicorn 설정 및 docker-compose, dockerfile 수정

- client/src/pages/MonthlyReport/MonthlyReport.tsx
> ### Title
>
> - 제목은 '[Feat] 홈 페이지 구현'과 같이 작성합니다.
> ### PR Type
>
> - [] FIX: 버그 수정
>
보고서 조건부
>
> - 추후 논의할 점에 대해 작성해주세요.
> Feat : 예산 중 지출 금액 조건부 표현식으로 변환

- server/budgets/views.py
- server/expenses/views.py
> ### Title
> Feat: 예산 삭제 기능 및 총합 계산 추가
> ### PR Type
> Feat: 예산 삭제 기능 및 총합 계산 추가

- server/budgets/models.py
- server/budgets/views.py
- server/config/settings.py
- server/expenses/models.py
- server/expenses/views.py
- server/members/views.py
> ### Title
> Fix: 예산 삭제 기능 수정 및 Integer필드 전체  -> BigInteger 로 수정
> ### PR Type
>
>
>
> Fix: 예산 삭제 기능 수정 및 Integer필드 전체  -> BigInteger 로 수정

- server/config/settings.py
- server/members/serializers.py
- server/members/views.py
> ### Title
> Fix: member 정보 수정시 name, password 빈칸 허용 수정
> Feat: 프로필 사진 업로드시 이미지 파일 사이즈 검증 추가
> ### PR Type
>
>
>
> Fix: member 정보 수정시 name, password 빈칸 허용 수정 및 프로필 사진 업로드시 이미지 파일 사이즈 검증 추가

- server/expenses/views.py
> ### Title
> Fix: HTTP_400_BAD_REQUEST 오타 수정
> ### PR Type
>
>
>
> Fix: HTTP_400_BAD_REQUEST 오타 수정

- server/budgets/serializers.py
- server/budgets/views.py
- server/config/settings.py
- server/expenses/serializers.py
- server/expenses/views.py
- server/members/views.py
> ### Title
> Fix: 예산, 고정지출, 지출 생성 및 수정 시 빈값,0, 음수 저장 안되게 검증
> ### PR Type
>
>
>
> Fix: 예산, 고정지출, 지출 생성 및 수정 시 빈값,0, 음수 저장 안되게 검증

- client/src/components/BudgetNExpensesTables/BudgetHistoryTableCell.tsx
- client/src/components/BudgetNExpensesTables/ExpensesRegiTableCell.css.ts
- client/src/components/BudgetNExpensesTables/ExpensesRegiTableCell.tsx
- client/src/components/SideBar.tsx/SideBar.tsx
- client/src/pages/BudgetNExpenses/BudgetNExpenses.css.ts
- client/src/pages/BudgetNExpenses/BudgetNExpenses.tsx
> ### Title
>
> Feat : 예산 삭제기능 추가, 음수는 입력할 수 없게 설정, Style : 고정 지출 테이블과 스타일 동일하게 맞추기
> ### PR Type
>
> - [X] FEAT: 새로운 기능 구현
> - [X] STYLE: 포맷팅 변경
>
> 예산 삭제 기능 추가
> 음수 입력 못하게
> 고정 지출 테이블 스타일 수정
> 사이드 바 리렌더링 되게 수정
>
> - 추후 논의할 점에 대해 작성해주세요.
> Feat : 예산 삭제기능 추가, 음수는 입력할 수 없게 설정, Style : 고정 지출 테이블과 스타일 동일하게 맞추기

- client/src/components/SideBar.tsx/SideBar.tsx
- client/src/pages/BudgetNExpenses/BudgetNExpenses.tsx
- client/src/pages/MainPage/Main.tsx
>
> - [Feat] total_Budget으로 적용, [Chore] 사이드 바  없을 때 0 뜨는거 제거, 예산 등록에서 text Field 비우기 여기서 해버림
> ### PR Type
>
> - [X] FEAT: 새로운 기능 구현
>
> - total_Budget으로 적용
> - 사이드 바 없을 때 0 뜨는거 없애기
> - 예산 등록에서 text Field 숫자 아니면 입력 못 받도록 재수정
> - 예산 등록하면 Text Field 비우기 적용
>
> [Feat] total_Budget으로 적용, [Chore] 사이드 바  없을 때 0 뜨는거 제거, 예산 등록에서 text Field 비우기 여기서 해버림

- client/src/components/BudgetNExpensesTables/ExpensesRegiTableCell.tsx
- client/src/components/BudgetRegTable/BudgetRegTable.tsx
- client/src/components/Charts/DoughnutChartCategory.tsx
- client/src/components/ExpendituresList/ExpenditureList.tsx
- client/src/components/SideBar.tsx/FixedExpenses/FixedExpenses.tsx
- client/src/pages/MonthlyReport/MonthlyReport.tsx
>
> - [Chore]  레포트 페이지 total_Budget으로 변경, 기타 다른 페이지  카테고리 선택, 지불수단 선택하는 부분 list label 수정
> ### PR Type
>
>
> - 레포트 페이지 total_Budget으로 값 받는 걸로 변경
> - 카테고리 선택, 지불수단 선택하는 부분들 list label 수정
>
> [Chore]  레포트 페이지 total_Budget으로 변경, 기타 다른 페이지  카테고리 선택, 지불수단 선택하는 부분 list label 수정

- server/members/urls.py
- server/members/views.py
- server/poetry.lock
- server/pyproject.toml
> ### Title
> Feat: KaKao 소셜 로그인 기능 구현
> ### PR Type
>
>
>
> Feat: KaKao 소셜 로그인 기능 구현

- server/config/settings.py
- server/members/views.py
> ### Title
> Fix: 카카오 소셜 로그인 수정
> ### PR Type
>
>
>
> Fix: 카카오 소셜 로그인 수정

- server/config/settings.py
> ### Title
> Fix: allow hosts 허용 호스트 변경
> ### PR Type
>
>
>
> Fix: allow hosts 허용 호스트 변경

- server/members/models.py
- server/members/views.py
> ### Title
> Feat: kakao logout 기능 구현
> ### PR Type
>
>
>
> Feat: kakao logout 기능 구현

- server/budgets/models.py
- server/expenses/models.py
- server/members/views.py
> ### Title
> Fix: 예산, 고정지출, 지출 models.py 수정 kakao 로그인 오류 수정
> ### PR Type
>
>
>
> Fix: 예산, 고정지출, 지출 models.py 수정 kakao 로그인 오류 수정

- server/members/views.py
> ### Title
> Fix: 프로필 사진 권한 공개 버그 수정
> ### PR Type
>
>
>
> Fix: 프로필 사진 권한 공개 버그 수정
